version: '3.9'

services:
  app:
    build:
      context: .
    environment:
      SERVER_IP_ADDRESS: ${SERVER_IP_ADDRESS}
      SERVER_PORT: ${SERVER_PORT}
    ports:
        - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
        - .:/http-server
    env_file:
      - .env
